-- Databricks notebook source
-- MAGIC %md
-- MAGIC ### Example Exploratory Notebook
-- MAGIC
-- MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
-- MAGIC
-- MAGIC **Note**: This notebook is not executed as part of the pipeline.

-- COMMAND ----------

USE CATALOG `my_lab`;
USE SCHEMA `handson`;

-- COMMAND ----------

DESCRIBE HISTORY my_lab.handson.sdp_example_silver_audit

-- COMMAND ----------

-- CDF(チェンジデータフィード)を参照
SELECT *
FROM table_changes('my_lab.handson.sdp_example_silver_audit', 1, 4);
